<a href="https://colab.research.google.com/github/feracor/pandas_numpy/blob/main/2_dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dimensiones

In [ ]:
import numpy as np

In [ ]:
scalar = np.array(12)
print(scalar)
scalar.ndim

12


0

In [ ]:
vector = np.array([1, 2, 3, 4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [ ]:
matriz = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
tensor = np.array([[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


3

In [ ]:
tensor4 = np.array([[[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]],[[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]]])
print(tensor4)
tensor4.ndim

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]]


4

In [ ]:
#Agregar dimensiones
vector = np.array([1, 2, 3, 4], ndmin = 10) # Crea un tensor con dimensiones específicas dentro del parámetro ndmin=
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0) # Expande el array en axis=0, que es a nivel de filas. Se convierte de vector a matriz
print(expand)
print(expand.ndim)

expand2 = np.expand_dims(np.array([1, 2, 3]), axis=1) # Expande el array en axis=1, que es a nivel de columnas. Se convierte de vector a matriz
print(expand2)
print(expand2.ndim)

[[1 2 3]]
2
[[1]
 [2]
 [3]]
2


In [ ]:
#Reducir dimensiones
vector = np.array([1, 2, 3, 4], ndmin = 10)
print(vector, vector.ndim)

vector_2 = np.squeeze(vector) # Médoto squeeze elimina las dimensiones que no se usan
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]] 10
[1 2 3 4] 1


In [ ]:
tensor = np.array([[1,2,3],[4,5,3],[6,7,8]], ndmin=5) # Crea tensor de 5 dimensiones
print(tensor, tensor.ndim)
tensor = np.squeeze(tensor) # Tensor se reduce a 3 dimensiones, que son las que se consideran útiles
print(tensor, tensor.ndim)

[[[[[1 2 3]
    [4 5 3]
    [6 7 8]]]]] 5
[[1 2 3]
 [4 5 3]
 [6 7 8]] 2


#Creando arrays desde NumPy

In [ ]:
a = np.arange(10) # Método que crea un arreglo dentro de un rango dado. Comienza desde 0 hasta el ingresado menos uno
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(3, 10) # Crea un arreglo dentro de un rango dado hasta el límite superior menos uno
b

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
c = np.arange(-2, -16, -1) # Crea un arreglo dentro de un rango, y hace un decremento de -1 hasta llegar al límite
c

array([ -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13, -14,
       -15])

In [ ]:
d = np.arange(2, 15, 2) # Crea un array que salta de dos en dos
d

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
np.zeros(3) #Crear array con ceros

array([0., 0., 0.])

In [ ]:
np.zeros([10,10]) #Crear array con ceros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones([10,10]) #Crear array con unos

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,10) #Crea array con valor de inicio, valor límite, cuántos datos se van a generar de manera normalizada

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.linspace(0,10) #Crea array con valor de inicio, valor límite, cuántos datos se van a generar de manera normalizada

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.eye(4) #Crea una matriz diagonal de dimesiones dadas

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(10) #Crea una matriz diagonal de dimesiones dadas

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand() #Genera un array con un valor aleatorio entre 0 y 1

0.03566557159615191

In [ ]:
np.random.rand(4,3) #Genera un array con un valores aleatorio entre 0 y 1 de dimensiones dadas

array([[0.89462056, 0.29063108, 0.91570012],
       [0.59131316, 0.25629309, 0.84969637],
       [0.34700841, 0.40925723, 0.55382257],
       [0.83820439, 0.8886847 , 0.71911612]])

In [ ]:
np.random.randint(1,15) # Genera un entero con un valor aleatorio dento de los límites dados

4

In [ ]:
np.random.randint(1,15, (10, 10)) #Crea un array y genera valores entero con un valor aleatorio dento de los límites dados en una estructura definida

array([[ 1, 14,  6,  7,  4,  8, 10,  1,  1,  5],
       [13, 12,  8,  8,  2,  7, 12, 11,  3, 14],
       [10,  8,  5,  1,  7,  3, 13,  1,  3,  3],
       [ 7, 14,  7,  9,  2,  1,  2, 12,  8, 11],
       [ 2, 13, 10,  9,  9, 13, 10, 14, 14, 11],
       [ 8,  3,  6,  4,  4, 14,  5,  2,  6, 13],
       [ 4,  2,  5,  4,  2,  5, 11, 10,  6,  2],
       [ 3,  3, 14,  7,  6,  4,  6,  2, 10,  6],
       [10,  6, 12,  5, 13,  6, 12,  5, 13, 11],
       [ 6,  5,  9, 14,  2,  1, 13,  9, 11, 14]])

In [ ]:
np.random.randint(1,15, (3, 2, 4))#Crea un tensor y genera valores entero con un valor aleatorio dento de los límites dados en una estructura definida

array([[[ 3,  6,  9,  1],
        [ 5, 10,  6,  7]],

       [[13,  4,  3,  2],
        [ 8,  1,  1,  5]],

       [[ 2,  5,  3,  5],
        [ 4, 10,  9, 11]]])

#Shape y Reshape

In [ ]:
#Shape es la forma del arreglo, es decir el tipo de estructura

a = np.random.randint(1,10, (3,2))
print(a, a.ndim)
a.shape

[[2 7]
 [5 9]
 [7 1]] 2


(3, 2)

In [ ]:
b = a.reshape(1,6) # Cambia la forma del array y ajusta los elementos para que se ajusten
c = a.reshape(2,3)
print(a,'\n',b,'\n', c,'\n', b.ndim,'\n', a.shape)


[[2 7]
 [5 9]
 [7 1]] 
 [[2 7 5 9 7 1]] 
 [[2 7 5]
 [9 7 1]] 
 2 
 (3, 2)


In [ ]:
np.reshape(a, (1,6)) # Esta forma simplifica la sintaxis

array([[2, 7, 5, 9, 7, 1]])

In [ ]:
print(a)
np.reshape(a, (2,3), 'C') # Reorganiza basándose en el lenguaje de C, tomando elementos de izq a der en filas

[[2 7]
 [5 9]
 [7 1]]


array([[2, 7, 5],
       [9, 7, 1]])

In [ ]:
print(a)
np.reshape(a, (2,3), 'F') # Reorganiza basándose en el lenguaje de Fortran, tomando elementos de izq a der en columnas

[[2 7]
 [5 9]
 [7 1]]


array([[2, 7, 9],
       [5, 7, 1]])

In [ ]:
print(a)
np.reshape(a, (2,3), 'A') # Reorganiza basándose en el lenguaje que tiene mi sistema optimizado, en mi caso es C

[[2 7]
 [5 9]
 [7 1]]


array([[2, 7, 5],
       [9, 7, 1]])

In [ ]:
e = np.reshape(a, (1,7)) #Arroja error ya que al usar el reshape, es necesario que las nuevas dimensiones respeten la cantidad de elementos del array original

ValueError: cannot reshape array of size 6 into shape (1,7)

#Funciones principales de NumPy

In [ ]:
a = np.random.randint(1, 20, 10)
a

array([ 3, 16, 11,  1, 10,  8, 16, 19, 11, 13])

In [ ]:
b = a.reshape(2, 5)
b

array([[ 3, 16, 11,  1, 10],
       [ 8, 16, 19, 11, 13]])

In [ ]:
b.max() #Trar el valor máximo del array

19

In [ ]:
b.max(1) #Trar lor valores máximos de cada fila

array([16, 19])

In [ ]:
b.max(0) #Trar lor valores máximos de cada columna

array([ 8, 16, 19, 11, 13])

In [ ]:
b.argmax() #Trae el indice que contiene el valor máximo en todo el array

7

In [ ]:
b.argmax(1) #Trae el indice que contiene el valor máximo por fila

array([1, 2])

In [ ]:
b.argmax(0) #Trae el indice que contiene el valor máximo por columna

array([1, 0, 1, 1, 1])

In [ ]:
b.argmin() #Trae el indice que contiene el valor mínimo en todo el array

3

In [ ]:
b.argmin(1) #Trae el indice que contiene el valor mínimo por columna

array([3, 0])

In [ ]:
b.argmin(0) #Trae el indice que contiene el valor mínimo por columna

array([0, 0, 0, 0, 0])

In [ ]:
b.ptp() #Peack to Peack muestra la diferencia entre el valor máximo y mínimo de todo el array

18

In [ ]:
b.ptp(1) #Peack to Peack muestra la diferencia entre el valor máximo y mínimo de todo el array

array([15, 11])

In [ ]:
b.ptp(0) #Peack to Peack muestra la diferencia entre el valor máximo y mínimo en columnas

array([ 5,  0,  8, 10,  3])

In [ ]:
b.ptp(1) #Peack to Peack muestra la diferencia entre el valor máximo y mínimo en filas

array([15, 11])

In [ ]:
np.percentile(b,50) #Valor que se encuentra en la mitad

11.0

In [ ]:
b

array([[ 3, 16, 11,  1, 10],
       [ 8, 16, 19, 11, 13]])

In [ ]:
b.sort() #Ordena los elementos de menor a mayor
b

array([[ 1,  3, 10, 11, 16],
       [ 8, 11, 13, 16, 19]])

In [ ]:
np.median(b) #Obtener mediana

11.0

In [ ]:
np.median(b, 0) #Obtener mediana por columnas

array([ 4.5,  7. , 11.5, 13.5, 17.5])

In [ ]:
np.median(b, 1) #Obtener mediana por filas

array([10., 13.])

In [ ]:
np.std(b) #Desviación estandar

5.4

In [ ]:
np.var(b) #Varianza

29.160000000000004

In [ ]:
np.mean(b) #Media

10.8

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([5,6])
b

array([5, 6])

In [ ]:
np.concatenate((a, b), axis=1) #Para hace una concatenacion, las dimensiones de los arreglos deben ser iguales

TypeError: concatenate() got multiple values for argument 'axis'

In [ ]:
a.ndim

2

In [ ]:
b.ndim

1

In [ ]:
c1 = np.expand_dims(b, axis=0) #Ordena arreglo por columnas
print(c1,c1.shape)

[[5 6]] (1, 2)


In [ ]:
c2 = np.expand_dims(b, axis=1) #Ordena arreglo por filas
print(c2, c2.shape)

[[5]
 [6]] (2, 1)


In [ ]:
np.concatenate((a, c1), axis=0) #Hace concatenacion por filas con el array de (1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a, c2), axis=1) #Hace concatenacion por columnas con el array de (2,1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
c1

array([[5, 6]])

In [ ]:
c1.T #Realiza la traspuesta de la matriz

array([[5],
       [6]])