<a href="https://colab.research.google.com/github/feracor/pandas_numpy/blob/main/3_copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Copy

In [ ]:
import numpy as np

In [ ]:
a = np.arange(0,11) #Crear un arreglo
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a1 = a[0:6] #Hacer slicing y guardar en otro objeto. Al hacer uso de este recurso se hace una referencia en memoría.
a1

array([0, 1, 2, 3, 4, 5])

In [ ]:
a1[:] = 0 #Inicializar el objeto con ceros
a1

array([0, 0, 0, 0, 0, 0])

In [ ]:
a #Al verificar el arreglo original, se han modificado los elementos que estaban en el arreglo modificable

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
a2 = a.copy() #Para evitar errores de referencia, se usa el método copy
a2

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
a2[:] = 100 #Al hacer modificaciones en el arreglo nuevo, ya no se va a afectar el original
a2

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
a #Cuando se quiera realizar modificaciones y no afectar el array original, se sugiere usar el método copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

#Condiciones

In [ ]:
a = np.linspace(1,10,10, dtype='int8')
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
a > 5 #Retorna una lista boolena analizando cada elemento y verificando los que cumplen con la condición

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
a_cond = a > 5
a_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
a[0] # Trae elementos por index
a[a_cond] #Trae elementos que cumplen con la condición el array a_cond

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
a[a > 5] #Trae elementos que cumplen con la condición definida

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
a[(a > 5) & (a < 8)] #Trae elementos entre un rango establecido con dos condiciones

array([6, 7], dtype=int8)

In [ ]:
a1 = a.copy()
a1[(a > 5)] = 00 #Este condicional reemplaza los valora a 00 en los elementos que cumplan con la condición
a1

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0], dtype=int8)

In [ ]:
a1[a1==00]

array([0, 0, 0, 0, 0], dtype=int8)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

#Operaciones

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
lista * 2 #Al querer multiplicar, python duplica, pero no multiplica

[1, 2, 1, 2]

In [ ]:
a = np.arange(10)
a1 = a.copy()
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 * 2 #El arreglo en numpy si permite ser operado aritméricamente

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
11 / a1 #Se da una advertencia que dice que no se puede dividir por cero, sin embargo, entrega los demás resultados

<ipython-input-53-c3928c275e7d>:1: RuntimeWarning: divide by zero encountered in divide
  11 / a1 #Se da una advertencia que dice que no se puede dividir por cero, sin embargo, entrega los demás resultados


array([        inf, 11.        ,  5.5       ,  3.66666667,  2.75      ,
        2.2       ,  1.83333333,  1.57142857,  1.375     ,  1.22222222])

In [ ]:
a + a1 #Puede realizar operaciones entre array de uno en uno (posición)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a * a1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a ** a1

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [ ]:
matriz1 = a1.reshape(2,5)
matriz2 = matriz1.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz1 + matriz2 #Se hacen operaciones index por intex

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
np.matmul(matriz1, matriz2.T) #Realizar producto punto con método

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz1 @ matriz2.T #Realizar producto punto con @

array([[ 30,  80],
       [ 80, 255]])