<a href="https://colab.research.google.com/github/feracor/pandas_numpy/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Array

In [2]:
import numpy as np

In [ ]:
lista = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # Crear una lista
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
arr = np.array(lista) # Convertir lista en array con NumPy
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # Crear matriz
print(type(matriz))
print(matriz)

matriz = np.array(matriz) # Convierte la matriz en un array de np
print(type(matriz))
print(matriz)

<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr[0] #El indexado de los array comienzan desde 0

1

In [ ]:
arr[0] + arr[5] # Se pueden hacer opertaciones entre elementos cuando se especifíca el index

7

In [ ]:
matriz[0] # Se imprime fila 0

array([1, 2, 3])

In [ ]:
matriz[0, 2] # Imprime a modo de coordenara [fila, columna]

3

In [ ]:
print(arr)
print(arr[0:3]) # Se hace un slicing para traer elementos específicos del array [inicio : fin]
print(arr[1:4]) # Se puede traer elementos de posiciones especificas
print(arr[:5]) # Se puede traer elementos sin especificar el inicio
print(arr[3:]) # Se puede traer elementos sin especificar el final
print(arr[:]) # Toma todos los elementos
print(arr[::3]) # Toma todos los elementos de 3 en 3 desde el index 0

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3]
[2 3 4]
[1 2 3 4 5]
[ 4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


In [ ]:
print(arr[-1]) # Toma el úlimo elemento
print(arr[-4]) # Cuenta desde el último elemento hasta el solicitado

10
7


In [ ]:
print(matriz)
print(type(matriz))

print(matriz[1:]) # Toma las posiciones desde la fila 1

print(matriz[1:, 1:3]) # Toma las posiciones desde la fila 1 y las columnas entre la 1 y 3
print(matriz[1:, 0:2]) # Toma las posiciones desde la fila 1 y las columnas entre la 0 y 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[4 5]
 [7 8]]


#Tipos de datos

In [20]:
arr_dato  = np.array([1, 2, 3, 4, 5, 6])
arr_dato.dtype # Muestra el tipo de dato dentro del array

dtype('int64')

In [21]:
arr_dato  = np.array([1, 2, 3, 4, 5, 6], dtype = 'float64') # Se puede definir el tipo de dato del objeto array para que sea compatible con las tareas que queremos realizar
print(arr_dato)
arr_dato.dtype # Muestra el tipo de dato dentro del array

[1. 2. 3. 4. 5. 6.]


dtype('float64')

In [27]:
arr_dato  = np.array([1, 2, 3, 4, 5, 6]) # Por defecto crea un array de tipo int64
print(arr_dato.dtype)
arr_dato = (arr_dato.astype(np.float64)) # Si el array ya viene definido con un tipo de dato, es posible hacer el casteo con el método .astype() y definir el tipo de dato que se desea
print(arr_dato.dtype)

int64
float64


In [33]:
arr = np.array([0, 1, 2, -1, -5])
arr = arr.astype(np.bool_) # Al convertir el tipo de dato a booleano, este interpreta el 0 como False y qualquier otro valor como True
arr

array([False,  True,  True,  True,  True])

In [44]:
arr = np.array([0, 1, 2, -1, -5])
arr = arr.astype(np.string_) # Al convertir el tipo de dato a string, convierte los valores númericos a carácteres de tipo string
arr

array([b'0', b'1', b'2', b'-1', b'-5'], dtype='|S21')

In [49]:
arr = np.array(['0', '1', '2', '-1', '-5'])
arr = arr.astype(np.int8) # Conversión de string a int8
arr

array([ 0,  1,  2, -1, -5], dtype=int8)

In [56]:
'''EN LOS ARRAY PUEDE HABER UN ÚNICO TIPO DE DATO'''
arr = np.array(['hola','0', '1', '2', '-1', '-5'])
arr = arr.astype(np.int8) # Conversión de string a int8 que generar error ya que no se pueden convertir carácteres alfabéticos en númericos
arr

ValueError: invalid literal for int() with base 10: 'hola'

In [52]:
a = np.arange(10) # Método que crea un arreglo dentro de un rango dado. Comienza desde 0 hasta el ingresado menos uno
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
b = np.arange(3, 10) # Crea un arreglo dentro de un rango dado hasta el límite superior menos uno
b

array([3, 4, 5, 6, 7, 8, 9])

In [55]:
arr = np.arange(-2, -16, -1) # Crea un arreglo dentro de un rango, y hace un decremento de -1 hasta llegar al límite
print(arr)

[ -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15]


#Dimensiones