<a href="https://colab.research.google.com/github/feracor/pandas_numpy/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Array

In [ ]:
import numpy as np

In [ ]:
lista = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
arr = np.array(lista)
print(type(arr))
arr


<class 'numpy.ndarray'>


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(type(matriz))
print(matriz)

matriz = np.array(matriz)
print(type(matriz))
print(matriz)


<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr[0] #El indexado de los array comienzan desde 0

1

In [ ]:
arr[0] + arr[5]

7

In [ ]:
matriz[0] # Se imprime fila 0

array([1, 2, 3])

In [ ]:
matriz[0, 2] # Imprime a modo de coordenara [fila, columna]

3

In [ ]:
print(arr)
print(arr[0:3]) # Se hace un slicing para traer elementos específicos del array [inicio : fin]
print(arr[1:4]) # Se puede traer elementos de posiciones especificas
print(arr[:5]) # Se puede traer elementos sin especificar el inicio
print(arr[3:]) # Se puede traer elementos sin especificar el final
print(arr[:]) # Toma todos los elementos
print(arr[::3]) # Toma todos los elementos de 3 en 3 desde el index 0

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3]
[2 3 4]
[1 2 3 4 5]
[ 4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


In [ ]:
print(arr[-1]) # Toma el úlimo elemento
print(arr[-4]) # Cuenta desde el último elemento hasta el solicitado

10
7


In [ ]:
print(matriz)
print(type(matriz))

print(matriz[1:]) # Toma las posiciones desde la fila 1

print(matriz[1:, 1:3]) # Toma las posiciones desde la fila 1 y las columnas entre la 1 y 3
print(matriz[1:, 0:2]) # Toma las posiciones desde la fila 1 y las columnas entre la 0 y 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[4 5]
 [7 8]]


#Tipos de datos