<a href="https://colab.research.google.com/github/feracor/pandas_numpy/blob/main/copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Copy

In [3]:
import numpy as np

In [4]:
a = np.arange(0,11) #Crear un arreglo
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a1 = a[0:6] #Hacer slicing y guardar en otro objeto. Al hacer uso de este recurso se hace una referencia en memoría.
a1

array([0, 1, 2, 3, 4, 5])

In [6]:
a1[:] = 0 #Inicializar el objeto con ceros
a1

array([0, 0, 0, 0, 0, 0])

In [7]:
a #Al verificar el arreglo original, se han modificado los elementos que estaban en el arreglo modificable

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [8]:
a2 = a.copy() #Para evitar errores de referencia, se usa el método copy
a2

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [9]:
a2[:] = 100 #Al hacer modificaciones en el arreglo nuevo, ya no se va a afectar el original
a2

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [10]:
a #Cuando se quiera realizar modificaciones y no afectar el array original, se sugiere usar el método copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

#Condiciones

In [34]:
a = np.linspace(1,10,10, dtype='int8')
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [14]:
a > 5 #Retorna una lista boolena analizando cada elemento y verificando los que cumplen con la condición

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [17]:
a_cond = a > 5
a_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [20]:
a[0] # Trae elementos por index
a[a_cond] #Trae elementos que cumplen con la condición el array a_cond

array([ 6,  7,  8,  9, 10], dtype=int8)

In [21]:
a[a > 5] #Trae elementos que cumplen con la condición definida

array([ 6,  7,  8,  9, 10], dtype=int8)

In [30]:
a[(a > 5) & (a < 8)] #Trae elementos entre un rango establecido con dos condiciones

array([6, 7], dtype=int8)

In [37]:
a1 = a.copy()
a1[(a > 5)] = 00 #Este condicional reemplaza los valora a 00 en los elementos que cumplan con la condición
a1

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0], dtype=int8)

In [38]:
a1[a1==00]

array([0, 0, 0, 0, 0], dtype=int8)

In [39]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)