<a href="https://colab.research.google.com/github/feracor/pandas_numpy/blob/main/copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Copy

In [1]:
import numpy as np

In [7]:
a = np.arange(0,11) #Crear un arreglo
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a1 = a[0:6] #Hacer slicing y guardar en otro objeto. Al hacer uso de este recurso se hace una referencia en memoría.
a1

array([0, 0, 0, 0, 0, 0])

In [13]:
a1[:] = 0 #Inicializar el objeto con ceros
a1

array([0, 0, 0, 0, 0, 0])

In [14]:
a #Al verificar el arreglo original, se han modificado los elementos que estaban en el arreglo modificable

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [15]:
a2 = a.copy() #Para evitar errores de referencia, se usa el método copy
a2

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [16]:
a2[:] = 100 #Al hacer modificaciones en el arreglo nuevo, ya no se va a afectar el original
a2

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
a

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])