<a href="https://colab.research.google.com/github/feracor/pandas_numpy/blob/main/dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dimensiones

In [1]:
import numpy as np

In [2]:
scalar = np.array(12)
print(scalar)
scalar.ndim

12


0

In [3]:
vector = np.array([1, 2, 3, 4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [4]:
matriz = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [6]:
tensor = np.array([[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


3

In [7]:
tensor4 = np.array([[[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]],[[[1, 2, 3],[4, 5, 6], [7, 8, 9]],[[10, 11, 12], [13, 14, 15], [16, 17, 18]]]])
print(tensor4)
tensor4.ndim

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]]


4

In [8]:
#Agregar dimensiones
vector = np.array([1, 2, 3, 4], ndmin = 10) # Crea un tensor con dimensiones específicas dentro del parámetro ndmin=
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4]]]]]]]]]]


10

In [16]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0) # Expande el array en axis=0, que es a nivel de filas. Se convierte de vector a matriz
print(expand)
print(expand.ndim)

expand2 = np.expand_dims(np.array([1, 2, 3]), axis=1) # Expande el array en axis=1, que es a nivel de columnas. Se convierte de vector a matriz
print(expand2)
print(expand2.ndim)

[[1 2 3]]
2
[[1]
 [2]
 [3]]
2


In [18]:
#Reducir dimensiones
vector = np.array([1, 2, 3, 4], ndmin = 10)
print(vector, vector.ndim)

vector_2 = np.squeeze(vector) # Médoto squeeze elimina las dimensiones que no se usan
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]] 10
[1 2 3 4] 1


In [28]:
tensor = np.array([[1,2,3],[4,5,3],[6,7,8]], ndmin=5) # Crea tensor de 5 dimensiones
print(tensor, tensor.ndim)
tensor = np.squeeze(tensor) # Tensor se reduce a 3 dimensiones, que son las que se consideran útiles
print(tensor, tensor.ndim)

[[[[[1 2 3]
    [4 5 3]
    [6 7 8]]]]] 5
[[1 2 3]
 [4 5 3]
 [6 7 8]] 2


#Creando arrays desde NumPy

In [32]:
a = np.arange(10) # Método que crea un arreglo dentro de un rango dado. Comienza desde 0 hasta el ingresado menos uno
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b = np.arange(3, 10) # Crea un arreglo dentro de un rango dado hasta el límite superior menos uno
b

array([3, 4, 5, 6, 7, 8, 9])

In [33]:
c = np.arange(-2, -16, -1) # Crea un arreglo dentro de un rango, y hace un decremento de -1 hasta llegar al límite
c

array([ -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13, -14,
       -15])

In [36]:
d = np.arange(2, 15, 2) # Crea un array que salta de dos en dos
d

array([ 2,  4,  6,  8, 10, 12, 14])

In [37]:
np.zeros(3) #Crear array con ceros

array([0., 0., 0.])

In [38]:
np.zeros([10,10]) #Crear array con ceros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.ones([10,10]) #Crear array con unos

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
np.linspace(0,10,10) #Crea array con valor de inicio, valor límite, cuántos datos se van a generar de manera normalizada

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [46]:
np.linspace(0,10) #Crea array con valor de inicio, valor límite, cuántos datos se van a generar de manera normalizada

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [47]:
np.eye(4) #Crea una matriz diagonal de dimesiones dadas

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.eye(10) #Crea una matriz diagonal de dimesiones dadas

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [50]:
np.random.rand() #Genera un array con un valor aleatorio entre 0 y 1

0.03566557159615191

In [53]:
np.random.rand(4,3) #Genera un array con un valores aleatorio entre 0 y 1 de dimensiones dadas

array([[0.89462056, 0.29063108, 0.91570012],
       [0.59131316, 0.25629309, 0.84969637],
       [0.34700841, 0.40925723, 0.55382257],
       [0.83820439, 0.8886847 , 0.71911612]])

In [62]:
np.random.randint(1,15) # Genera un entero con un valor aleatorio dento de los límites dados

4

In [65]:
np.random.randint(1,15, (10, 10)) #Crea un array y genera valores entero con un valor aleatorio dento de los límites dados en una estructura definida

array([[ 1, 14,  6,  7,  4,  8, 10,  1,  1,  5],
       [13, 12,  8,  8,  2,  7, 12, 11,  3, 14],
       [10,  8,  5,  1,  7,  3, 13,  1,  3,  3],
       [ 7, 14,  7,  9,  2,  1,  2, 12,  8, 11],
       [ 2, 13, 10,  9,  9, 13, 10, 14, 14, 11],
       [ 8,  3,  6,  4,  4, 14,  5,  2,  6, 13],
       [ 4,  2,  5,  4,  2,  5, 11, 10,  6,  2],
       [ 3,  3, 14,  7,  6,  4,  6,  2, 10,  6],
       [10,  6, 12,  5, 13,  6, 12,  5, 13, 11],
       [ 6,  5,  9, 14,  2,  1, 13,  9, 11, 14]])

In [69]:
np.random.randint(1,15, (3, 2, 4))#Crea un tensor y genera valores entero con un valor aleatorio dento de los límites dados en una estructura definida

array([[[ 3,  6,  9,  1],
        [ 5, 10,  6,  7]],

       [[13,  4,  3,  2],
        [ 8,  1,  1,  5]],

       [[ 2,  5,  3,  5],
        [ 4, 10,  9, 11]]])

#Shape y Reshape

In [70]:
#Shape es la forma del arreglo, es decir el tipo de esctructura
