<a href="https://colab.research.google.com/github/feracor/pandas_numpy/blob/main/dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dimensiones

In [1]:
import numpy as np

In [3]:
scalar = np.array(12)
print(scalar)
scalar.ndim

12


0

In [5]:
vector = np.array([1, 2, 3, 4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [6]:
matriz = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2